-- v9: No-password profile selector.
-- Run this in Supabase Dashboard > SQL Editor > New query.
-- IMPORTANT: this version does NOT use Supabase Auth or Row Level Security.
-- Data is separated by the email address entered in the app. Anyone who knows
-- another person's email address can access that profile, so do not use this
-- version for sensitive/private information.

create table if not exists public.food_logs (
  id bigint generated by default as identity primary key,
  user_email text not null,
  log_date date not null,
  meal text not null check (meal in ('Breakfast','Lunch','Dinner','Snacks')),
  food_name text not null,
  quantity numeric not null,
  unit text not null,
  calories numeric not null default 0,
  protein numeric not null default 0,
  carbs numeric not null default 0,
  fat numeric not null default 0,
  fiber numeric not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.weight_logs (
  id bigint generated by default as identity primary key,
  user_email text not null,
  weight_date date not null,
  weight_kg numeric not null check (weight_kg > 0),
  note text default '',
  created_at timestamptz not null default now(),
  unique(user_email, weight_date)
);

create table if not exists public.custom_foods (
  id bigint generated by default as identity primary key,
  user_email text not null,
  name text not null,
  category text not null default 'Other',
  serving_qty numeric not null default 1,
  unit text not null default 'serving',
  calories numeric not null default 0,
  protein numeric not null default 0,
  carbs numeric not null default 0,
  fat numeric not null default 0,
  fiber numeric not null default 0,
  created_at timestamptz not null default now(),
  unique(user_email, name)
);

-- If these tables already exist from v8, the easiest migration is to create
-- fresh v9 tables. The statements below are provided for a clean new setup.
-- Do not run this file on top of v8 tables without first migrating them.

alter table public.food_logs disable row level security;
alter table public.weight_logs disable row level security;
alter table public.custom_foods disable row level security;

grant select, insert, update, delete on public.food_logs to anon, authenticated;
grant select, insert, update, delete on public.weight_logs to anon, authenticated;
grant select, insert, update, delete on public.custom_foods to anon, authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;
