-- Run this whole script in Supabase Dashboard > SQL Editor > New query.
create table if not exists public.food_logs (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  log_date date not null,
  meal text not null check (meal in ('Breakfast','Lunch','Dinner','Snacks')),
  food_name text not null,
  quantity numeric not null,
  unit text not null,
  calories numeric not null default 0,
  protein numeric not null default 0,
  carbs numeric not null default 0,
  fat numeric not null default 0,
  fiber numeric not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.weight_logs (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  weight_date date not null,
  weight_kg numeric not null check (weight_kg > 0),
  note text default '',
  created_at timestamptz not null default now(),
  unique(user_id, weight_date)
);

create table if not exists public.custom_foods (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  category text not null default 'Other',
  serving_qty numeric not null default 1,
  unit text not null default 'serving',
  calories numeric not null default 0,
  protein numeric not null default 0,
  carbs numeric not null default 0,
  fat numeric not null default 0,
  fiber numeric not null default 0,
  created_at timestamptz not null default now(),
  unique(user_id, name)
);

alter table public.food_logs enable row level security;
alter table public.weight_logs enable row level security;
alter table public.custom_foods enable row level security;

create policy "users manage their food logs" on public.food_logs
for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy "users manage their weight logs" on public.weight_logs
for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy "users manage their custom foods" on public.custom_foods
for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

grant select, insert, update, delete on public.food_logs to authenticated;
grant select, insert, update, delete on public.weight_logs to authenticated;
grant select, insert, update, delete on public.custom_foods to authenticated;
grant usage, select on all sequences in schema public to authenticated;
